## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: todolistapp
  properties:
    services:
      - name: ToDoService
        properties:
          description: ToDoService description.
          osType: Windows
          codePackages:
            - name: ToDoService
              image: todoservice:dev
              endpoints:
                - name: ToDoServiceListener
                  port: 80
#              environmentVariables:
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: "[parameters('ToDoService_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: todolistappNetwork
              endpointRefs:
                - name: ToDoServiceListener
