## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: todo_list
  properties:
    services:
      - name: ToDoService
        properties:
          description: ToDoService description.
          osType: Windows
          codePackages:
            - name: ToDoService
              image: todoservice:dev
              endpoints:
                - name: ToDoServiceListener
                  port: 20009
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20009
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: todo_listNetwork