## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: todolistapp
  properties:
    services:
      - name: WebFrontEnd
        properties:
          description: WebFrontEnd description.
          osType: Windows
          codePackages:
            - name: WebFrontEnd
              image: webfrontend:dev
              endpoints:
                - name: WebFrontEndListener
                  port: 80
              environmentVariables:
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
                 - name: ApiHostPort
                   value: 80
                 - name: ToDoServiceName
                   value: ToDoService
              resources:
                requests:
                  cpu: "[parameters('WebFrontEnd_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: todolistappNetwork
              endpointRefs:
                - name: WebFrontEndListener
