## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: VisualObjects
  properties:
    services:
      - name: web
        properties:
          description: web description.
          osType: Windows
          codePackages:
            - name: web
              image: web:dev
              endpoints:
                - name: webListener
                  port: 20005
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20005
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: VisualObjectsNetwork