## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: todo_list
  properties:
    services:
      - name: WebFrontEnd
        properties:
          description: WebFrontEnd description.
          osType: Windows
          codePackages:
            - name: WebFrontEnd
              image: webfrontend:dev
              endpoints:
                - name: WebFrontEndListener
                  port: 20002
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20002
                - name: AppName
                  value: todo_list
                - name: ApiHostPort
                  value: 20009
                - name: ServiceName
                  value: ToDoService
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: todo_listNetwork